### Handin 1


# Info

Everything should be completed and approved in person. Groups are fine.

The objectives for this handin is:
* Playing with numpy.
* Plotting with Plotly (as a preparation for using dash (https://plotly.com/dash/) later on)
* Train a more complex model using the Fortuna Algorithm.
* Route planning for Knut Knut Transport AS. 

## How to solve?
There should be a comment/section stating the objective of a task.  
And there should be a commented section labeled # -- CODE --  
that shows where to put your code. For tasks that are not answered by code you can either write the answer  
as a markup cell or write it on a seperate piece of paper.

In [1]:
import numpy as np


# TASK: Create a numpy array containing the whole numbers between 1, 10 (inclusive)

# -- CODE --
a = np.array(range(1,11)) 
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:


assert isinstance(a, np.ndarray)
assert np.isclose(a, [1,2,3,4,5,6,7,8,9,10]).all()
print("<ok>")

<ok>


In [3]:
# TASK: Reshape the array a so that it is a 2 by 4 array

a = np.array(range(0, 8))

# -- CODE --
a= a.reshape(2,4)
a.shape


(2, 4)

In [4]:

assert( a.shape == (2,4) )
print("<ok>")

<ok>


In [5]:
# TASK: multiply all the numbers in a by 2.


a = np.array([[1,2,3,4], [5,6,7,8]])

# -- CODE --
a *= 2
a


array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [6]:


assert a.shape == (2,4)
assert a.sum() == 72
print("<ok>")

<ok>


In [7]:
# TASK:  create a numpy array b that contains the sum of each row (axis 1) in a 

a = np.array([[1,2,3,4], [5,6,7,8]])

# -- CODE --
b = np.sum(a, axis=1)
b

array([10, 26])

In [8]:

assert b.shape == (2,)
assert (b == [10, 26]).all()
print("<ok>")

<ok>


In [9]:
# TASK:  create a numpy array b that contains the mean value of each column (axis 0) in a 
a = np.array([[1,2,3,4], [1,2,3,8]])

# -- CODE --
b = np.mean(a, axis=0)
b.shape


(4,)

In [10]:


assert b.shape == (4,)
assert (b == [1, 2, 3, 6]).all()
print("<ok>")

<ok>


In [11]:
# TASK:  stack the arrays a, b and c into an array called s (vertically)
# s should be equal to s_true (hint, look at the numpy function vstack )


a = np.array([1, 3])
b = np.array([2, 4])
c = np.array([3, 5])

# -- CODE --
s = np.array([a,b,c])
s


array([[1, 3],
       [2, 4],
       [3, 5]])

In [12]:

s_true = np.array([[1, 3], [2, 4], [3, 5]])
assert (s_true == s).all()

print("<ok>")

<ok>


In [13]:
# TASK:  Flatten the array a into a 1d array called f (hint: numpy has a function named flatten)

a = np.random.randn(2,2,2)
print(a)

# -- CODE --
f = a.flatten()
f

[[[ 1.4101613   2.00603341]
  [-1.58432932  1.47672856]]

 [[ 0.97555785  0.31842479]
  [-0.047439   -0.15432856]]]


array([ 1.4101613 ,  2.00603341, -1.58432932,  1.47672856,  0.97555785,
        0.31842479, -0.047439  , -0.15432856])

In [14]:

print("-"*50)
print(f)
assert f.ndim == 1
print("<ok>")

--------------------------------------------------
[ 1.4101613   2.00603341 -1.58432932  1.47672856  0.97555785  0.31842479
 -0.047439   -0.15432856]
<ok>


## Task 1 -- Plot functions and scatter plots using Plotly 

Change the code to perform the two following tasks:

(See Plotly: https://plotly.com/python/plotly-express/ for more info.)

**Line Plot)**

Plot the function f(x) = -0.69x^2 + 1.3x + 0.42 over the interval [0, 2.5], with 0.01 increments in x.

**Scatter Plot)**  

Plot the first 25 Fibbonachi numbers using a scatter plot.
(The example shows the first 5).




In [15]:
# installs plotly
!pip install plotly
!pip install "jupyterlab>=3" "ipywidgets>=7.6"

print("You may have to restart jupyter to see graphs in the notebook.")

You may have to restart jupyter to see graphs in the notebook.


In [16]:
import numpy as np
import plotly.express as px


# Change this code into the correct Line Plot
#Plot the function f(x) = -0.69x^2 + 1.3x + 0.42 over the interval [0, 2.5], with 0.01 increments in x.
def func(x):
    return np.array(-0.69*x**2 + 1.3*x + 0.42)


In [17]:
xs = [i * 0.01 for i in range(0, 250)]
xs


[0.0,
 0.01,
 0.02,
 0.03,
 0.04,
 0.05,
 0.06,
 0.07,
 0.08,
 0.09,
 0.1,
 0.11,
 0.12,
 0.13,
 0.14,
 0.15,
 0.16,
 0.17,
 0.18,
 0.19,
 0.2,
 0.21,
 0.22,
 0.23,
 0.24,
 0.25,
 0.26,
 0.27,
 0.28,
 0.29,
 0.3,
 0.31,
 0.32,
 0.33,
 0.34,
 0.35000000000000003,
 0.36,
 0.37,
 0.38,
 0.39,
 0.4,
 0.41000000000000003,
 0.42,
 0.43,
 0.44,
 0.45,
 0.46,
 0.47000000000000003,
 0.48,
 0.49,
 0.5,
 0.51,
 0.52,
 0.53,
 0.54,
 0.55,
 0.56,
 0.5700000000000001,
 0.58,
 0.59,
 0.6,
 0.61,
 0.62,
 0.63,
 0.64,
 0.65,
 0.66,
 0.67,
 0.68,
 0.6900000000000001,
 0.7000000000000001,
 0.71,
 0.72,
 0.73,
 0.74,
 0.75,
 0.76,
 0.77,
 0.78,
 0.79,
 0.8,
 0.81,
 0.8200000000000001,
 0.8300000000000001,
 0.84,
 0.85,
 0.86,
 0.87,
 0.88,
 0.89,
 0.9,
 0.91,
 0.92,
 0.93,
 0.9400000000000001,
 0.9500000000000001,
 0.96,
 0.97,
 0.98,
 0.99,
 1.0,
 1.01,
 1.02,
 1.03,
 1.04,
 1.05,
 1.06,
 1.07,
 1.08,
 1.09,
 1.1,
 1.11,
 1.12,
 1.1300000000000001,
 1.1400000000000001,
 1.1500000000000001,
 1.16,
 1.17,


In [18]:
ys = [func(x) for x in xs]
ys


[array(0.42),
 array(0.432931),
 array(0.445724),
 array(0.458379),
 array(0.470896),
 array(0.483275),
 array(0.495516),
 array(0.507619),
 array(0.519584),
 array(0.531411),
 array(0.5431),
 array(0.554651),
 array(0.566064),
 array(0.577339),
 array(0.588476),
 array(0.599475),
 array(0.610336),
 array(0.621059),
 array(0.631644),
 array(0.642091),
 array(0.6524),
 array(0.662571),
 array(0.672604),
 array(0.682499),
 array(0.692256),
 array(0.701875),
 array(0.711356),
 array(0.720699),
 array(0.729904),
 array(0.738971),
 array(0.7479),
 array(0.756691),
 array(0.765344),
 array(0.773859),
 array(0.782236),
 array(0.790475),
 array(0.798576),
 array(0.806539),
 array(0.814364),
 array(0.822051),
 array(0.8296),
 array(0.837011),
 array(0.844284),
 array(0.851419),
 array(0.858416),
 array(0.865275),
 array(0.871996),
 array(0.878579),
 array(0.885024),
 array(0.891331),
 array(0.8975),
 array(0.903531),
 array(0.909424),
 array(0.915179),
 array(0.920796),
 array(0.926275),
 array

In [19]:
fig = px.line(x=xs, y=ys, title="Line Plot")
fig.update_layout(xaxis_range=[0,2.5], yaxis_range=[-1,2])
fig.show()

In [20]:
# Change this code into the correct Scatter Plot (please take care of the axis)

xs = np.array([x for x in range(0,25)])
xs


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
def fib(x):
    array = np.array([])
    last = 0
    twolast = 0
    current = 0
    test = range(0, len(x))
    print(test)
    for i in range(0, len(x)):

        if i == 1:
            last = 1
        current = last + twolast
        array = np.append(array, current)
        twolast = last
        last =current

    
    return(array)
        
        

ys = fib(xs)
ys


range(0, 25)


array([0.0000e+00, 1.0000e+00, 2.0000e+00, 3.0000e+00, 5.0000e+00,
       8.0000e+00, 1.3000e+01, 2.1000e+01, 3.4000e+01, 5.5000e+01,
       8.9000e+01, 1.4400e+02, 2.3300e+02, 3.7700e+02, 6.1000e+02,
       9.8700e+02, 1.5970e+03, 2.5840e+03, 4.1810e+03, 6.7650e+03,
       1.0946e+04, 1.7711e+04, 2.8657e+04, 4.6368e+04, 7.5025e+04])

In [22]:


fig = px.scatter(x=xs, y=ys, title="Fibbonachi Scatter Plot")
fig.update_layout(xaxis_range=[0,24.5], yaxis_range=[-10_000,100_000])
fig.show()

# Task 2 -- Numpy and curve fitting

Fill in the function get_2polynomal_from_3_points(). You are required to use the  
function: np.linalg.solve() for the actual computation, i.e. the task is mainly   
about shaping the input so it fits the np.linalg.solve() function. Note: dont use polyfit().

The function should return a 1d numpy array, with shape = (3,) in the format a, b,c.  
Such that ax^2 + bx + c = y, goes through the points p0, p1, p2

HINT: How should a matrix equation be formed, so solving it gives us the coefficients for a polynomial?

Limitations:
* There should be NO loops or ifs! (for/while/if). 
* Numpy functions that might come handy: reshape, hstack, flatten, ones



In [23]:
import numpy as np

def get_2polynomal_from_3_points(p0: np.array, p1: np.array, p2: np.array) -> np.array:
    # -- CODE --
    a = np.array([[p0[0]**2,p0[0],1.0], [p1[0]**2,p1[0],1.0], [p2[0]**2,p2[0],1.0]])
    print(a)
    b =np.array([p0[1],p1[1],p2[1]])
    print(b)

    return np.linalg.solve(a,b)


In [24]:

point0 = np.array([0.147, 0.596])
point1 = np.array([0.7, 0.992])
point2 = np.array([2.06, 0.17])


In [25]:
polynomial_coefficients = get_2polynomal_from_3_points(point0, point1, point2)
assert(polynomial_coefficients.shape[0] == 3 and polynomial_coefficients.ndim == 1)

print("Polynomial: {:2f}x^2 + {:.2f}x + {:.2f}".format(*polynomial_coefficients))


if not np.isclose(polynomial_coefficients[0], -0.69, atol=0.01):
    print("x^2 coeff is wrong (a), should be close to -0.69")
    
if not np.isclose(polynomial_coefficients[1], 1.3, atol=0.01):
    print("x coeff is wrong (b), should be close to 1.3")
    
if not np.isclose(polynomial_coefficients[2], 0.42, atol=0.01):
    print("Constant factor (c) is wrong, should be close to 0.42")
    
if np.isclose(polynomial_coefficients, [-0.69, 1.3, 0.42], atol=0.01).all():
    print("Correct polynomial found.")

[[0.021609 0.147    1.      ]
 [0.49     0.7      1.      ]
 [4.2436   2.06     1.      ]]
[0.596 0.992 0.17 ]
Polynomial: -0.690280x^2 + 1.30x + 0.42
Correct polynomial found.


# Task 3 -- Simple random search

Find the triplet $a,b,c \in \{x \;|\; x \in \mathbb{Z} \text{ and } 450 > x > 0 \}$ 

Using a random search in the parameter space. Such that the following relations is satisfied: 

### a
$a = \begin{cases} c+11, & \text{if } b\text{ is even} \\ 2c-129, & \text{if } b\text{ is odd} \end{cases}$

### b
$b = (a \times c) \mod 2377$

### c
$c = \left( \sum\limits_{k=0}^{a-1} b - 7k \right) + 142$

**Also how many guesses were needed?**

Note that in math notation $\sum\limits_{k=1}^{5}k = 1+2+3+4+5$ 

Hint (to check if you got the right answer): The product $abc$ should be 255450 $\pm$ 20 
    
Can you find any optimizations besides multi-thread/multi-process?

In [26]:
import random
random.seed(42)
import threading

In [27]:
guesses = 0
b_c =[(b,c ) for b in range(1,450) for c in range(1,450)]
random.shuffle(b_c)
for b ,c in b_c:
    guesses +=1
    #print(f"Attempt: {guesses}")
    if (b % 2) == 0:
        a = c + 11
    else:
        a = 2*c - 129
    if ((a*c)%2377 == b and (sum(b-7*k for k in range(0,a)) + 142) == c and (0 < a < 450)):
        print(f"It took {guesses} attempts to get the correct a, b and c to have the product {a*b*c} with the given paramaters for a, b and c")
        break


It took 132960 attempts to get the correct a, b and c to have the product 255440 with the given paramaters for a, b and c


# Task 4 -- Revisit the Fortuna Algorithm

Below is a implementation of Fortuna that uses fits linear function $f_{\theta} = a x + b$ where $\theta = \{a,b\}$ to a function $g(x)$.  
However, as is evidently from the graph, $g(x)$ is not a linear function.  

1) Change the code to instead use $f_{\theta}(x) = \sum\limits_{k=1}^{3} \Psi_k \sin(\gamma_k (x + \omega_k)) $.  
  Such that $|\theta| = 9$, where each parameter $c$ in $\theta$ is in $[-4. 4]$.  
That is, $f_{\theta}(x)$ is a sum of three sin terms. **Do not change the range of the sample\_theta function.**

3) However, it seems Fortuna (on average) struggles to find the optimal parameters $\theta$.  
Therefore you will have to innovate and change the Fortuna algorithm so that it faster finds "better solutions".
What changes did you make and **why** did you make them, and how did you measure how efficient these changes were?  
A excellent solution here will have an expected best loss of less than 5 using 100000 guesses. (take the average over 100 runs).
**But ANY improvment is sufficient to pass!**  

4) Using your newly made modified Fortuna Algorithm optimize the function: $h(x) = \mu - (\zeta sin(\kappa x) )  (\tau (x + \lambda))$ .  
The y values for this function can be found in the numpy array ys_h_1 (in the code below).  
Also test the values for ys_h_2. (the x is the same for all functions).

Does your new and improved Fortuna outperform the regular fortuna on this function as well? Why?   
**Remember to change your model to match $h(x)$**


4) [**Optional**] Develop a multiprocces implemention of the Fortuna algorithm using python's multiprocessing library (https://docs.python.org/3/library/multiprocessing.html).  
How are the speed ups? Are Fortuna really suited to parallel execution?




In [28]:
%%time
# the magic %%time has to be the first line in the cell, and reports the total exec time of the cell.

import random
import numpy as np
import plotly.express as px
import tqdm


CPU times: total: 15.6 ms
Wall time: 28.5 ms


In [29]:

def predict(x, theta):
    # change to sum of 3 sin() terms. 
    # use np.sin() and not math.sin().
    #a, b = theta
    psi = theta[0:3]
    gamma = theta[3:6]
    omega = theta[6:9]
    resultatet = 0
    for k  in range(3):
        resultatet += psi[k] * np.sin(gamma[k] * (x + omega[k]))
    return resultatet


In [30]:


def sample_theta(size_of_theta):
    # Do NOT CHANGE.
    theta = np.random.uniform(-4, 4, size=size_of_theta)
    return theta


In [31]:


def get_loss(y_hat, ys):
    # No change needed, returns quadratic loss.
    loss = ((y_hat - ys)**2).sum()
    return loss


In [ ]:

xs = np.array([1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4])
ys = np.array([4.03, 4.19, 4.26, 4.25, 4.17, 4.03, 3.85, 3.63, 3.40, 3.16, 2.93, 2.72, 2.53, 2.39, 2.28, 2.21, 2.18, 2.19, 2.22, 2.27, 2.33, 2.39, 2.44, 2.45, 2.43, 2.36, 2.22, 2.02, 1.75, 1.41, 1.00, 0.52, -0.01, -0.60, -1.22, -1.86, -2.50, -3.13, -3.72, -4.27, -4.75, -5.15, -5.45, -5.65, -5.74, -5.70, -5.55, -5.29, -4.92, -4.44, -3.89, -3.26, -2.58, -1.86, -1.12, -0.39, 0.32, 0.98, 1.60, 2.14, 2.61, 2.99, 3.28, 3.47, 3.57])

# 
ys_h_1 = np.array([15.98, 21.42, 24.1, 23.87, 21.0, 16.11, 10.06, 3.79, -1.8, -6.01, -8.39, -8.82, -7.47, -4.77, -1.3, 2.31, 5.49, 7.81, 9.04, 9.18, 8.44, 7.15, 5.72, 4.54, 3.89, 3.9, 4.52, 5.54, 6.63, 7.39, 7.49, 6.7, 4.97, 2.44, -0.54, -3.48, -5.8, -6.98, -6.61, -4.51, -0.79, 4.2, 9.8, 15.21, 19.57, 22.09, 22.2, 19.63, 14.52, 7.41, -0.83, -9.07, -16.11, -20.83, -22.36, -20.27, -14.59, -5.91, 4.72, 15.9, 26.06, 33.69, 37.58, 36.94, 31.64])
ys_h_2 = np.array([5.87, 5.83, 5.74, 5.62, 5.48, 16.58, 18.21, 18.49, 17.54, 15.54, 4.15, 3.9, 3.65, 3.42, 3.2, -1.9, -3.32, -3.97, -3.91, -3.27, 2.38, 2.36, 2.39, 2.46, 2.57, 2.2, 1.93, 1.22, 0.17, -1.06, 4.18, 4.59, 5.04, 5.52, 6.02, -1.49, 0.74, 3.55, 6.75, 10.06, 9.39, 9.95, 10.5, 11.02, 11.52, 16.0, 12.82, 8.47, 3.21, -2.62, 13.61, 13.76, 13.84, 13.84, 13.77, -24.16, -22.03, -17.9, -11.95, -4.55, 11.63, 10.99, 10.27, 9.47, 8.61])

# change to the size of theta ( 9 ) (for h(x) how many parameters does it have?)
n_params = 9

losses =[]
best_theta = sample_theta(n_params)


In [33]:
steps_per_restart= 10_000#100_000
global_best_theta = None
global_best_loss = float("inf")


In [34]:

for _ in range(100):
    best_loss = float('inf')
    for _ in tqdm.tqdm(range(90_000)):  #100_000 
        curr_theta = sample_theta(n_params)
        y_hat = predict(xs, curr_theta)
        curr_loss = get_loss(y_hat, ys)
    for _ in range(steps_per_restart):
        mutation = np.random.normal(0,0.2, size=n_params)
        suggested_theta = curr_theta + mutation
        suggested_theta = np.clip(suggested_theta, -4, 4)
        suggested_loss = get_loss(predict(xs, suggested_theta), ys)
        if best_loss > curr_loss:
            curr_loss = suggested_loss
            curr_theta = suggested_theta
    if curr_loss < global_best_loss:
        global_best_loss = curr_loss
        global_best_theta = curr_theta 
            
    losses.append(best_loss)
print("\nbest loss found:", global_best_loss)
print("theta:", global_best_theta) 
    
fig = px.line(x=xs, y=ys, title="f(x) vs Fortuna solution")
fig.add_scatter(x=xs, y=predict(xs, best_theta), mode='lines', name="y_hat")
fig.update_layout(xaxis_range=[xs.min(),xs.max()], yaxis_range=[-6,6])
fig.show()


# to get a solid estimate -> you should train at least 100 models and take the average performance.



100%|██████████| 90000/90000 [00:02<00:00, 34118.71it/s]



best loss found: 310.42158925697146
theta: [-1.59965463  2.34098633  1.68966426  2.18915389  0.8324002  -0.29647597
  3.72961358  0.57936716 -1.17707593]


best loss found: 46.00, mutation: 0.15, range: 100_0, Steps: 100
best loss found: 43.03, mutation: 0.01, range: 100_0, Steps: 100
best loss found: 29.83, mutation: 0.01, range: 100_00, Steps: 10
best loss found: 10.00, mutation: 0.1, range: 100_00, Steps: 10
best loss found: 14.33, mutation: 0.05, range: 100_00, Steps: 10
best loss found: 5.20, mutation: 0.2, range: 10_000, Steps: 10
best loss found: 24.11, mutation: 0.3, range: 100_00, Steps: 10
best loss found: 23.66, mutation: 0.25, range: 100_00, Steps: 10
best loss found: 11.68, mutation: 0.175, range: 100_00, Steps: 10
best loss found: 19.93, mutation: 0.187, range: 100_00, Steps: 10
best loss found: 26.06, mutation: 0.225, range: 100_00, Steps: 10
best loss found: 18.35, mutation: 0.2, range: 200_00, Steps: 5
best loss found: 22.18, mutation: 0.1, range: 200_00, Steps: 5
best loss found: 13.02, mutation: 0.01, range: 200_00, Steps: 5
best loss found: 23.98, mutation: 0.05, range: 200_00, Steps: 5
best loss found: 16.18, mutation: 0.5, range: 200_00, Steps: 5
best loss found: 24.52, mutation: 0.3, range: 200_00, Steps: 5
best loss found: 19.58, mutation: 0.2, range: 25_000, Steps: 4
best loss found: 11.35, mutation: 0.2, range: 10_000, Steps: 10



colabs 
best loss found: 46.00, mutation: 0.15, range: 100_0, Steps: 100
best loss found: 43.03, mutation: 0.01, range: 100_0, Steps: 100
best loss found: 29.83, mutation: 0.01, range: 100_00, Steps: 10
best loss found: 10.00, mutation: 0.1, range: 100_00, Steps: 10
best loss found: 14.33, mutation: 0.05, range: 100_00, Steps: 10
best loss found: 5.20, mutation: 0.2, range: 100_00, Steps: 10
best loss found: 24.11, mutation: 0.3, range: 100_00, Steps: 10
best loss found: 23.66, mutation: 0.25, range: 100_00, Steps: 10
best loss found: 11.68, mutation: 0.175, range: 100_00, Steps: 10
best loss found: 19.93, mutation: 0.187, range: 100_00, Steps: 10
best loss found: 26.06, mutation: 0.225, range: 100_00, Steps: 10
best loss found: 18.35, mutation: 0.2, range: 200_00, Steps: 5
best loss found: 22.18, mutation: 0.1, range: 200_00, Steps: 5
best loss found: 7.41, mutation: 0.01, range: 500_00, Steps: 2
best loss found: 20.19, mutation: 0.1, range: 500_00, Steps: 2
best loss found: 13.48, mutation: 0.05, range: 500_00, Steps: 2

## New Fortuna

In [35]:
def predict(x, theta):
    # change to sum of 3 sin() terms. 
    # use np.sin() and not math.sin().
    #a, b = theta
    psi = theta[0:3]
    gamma = theta[3:6]
    omega = theta[6:9]
    resultatet = 0
    for k  in range(3):
        resultatet += psi[k] * np.sin(gamma[k] * (x + omega[k]))
    return resultatet

In [36]:
def sample_theta(size_of_theta):
    # Do NOT CHANGE.
    theta = np.random.uniform(-4, 4, size=size_of_theta)
    return theta


In [ ]:

def get_loss(y_hat, ys):
    # No change needed, returns quadratic loss.
    loss = ((y_hat - ys)**2).sum()
    return loss

# Task 5 -- Fortuna For Decision Trees

Implement a Decision Tree for solving the XOR problem.   
Here: there are 2 real valued inputs, x0, x1  (found in xs).  

And the DT should take these two as input and predict an output: 0 or 1.   
The true answer can be found in ys_true.


In [42]:
import numpy as np
rng = np.random.default_rng(42)
n_examples = 40

xs = rng.uniform(size=(n_examples, 2))

# make a true y
b = (xs>0.5).astype(int)
ys_true = np.logical_xor(b[:, 0], b[:, 1]).astype(int)



In [43]:
xs

array([[0.77395605, 0.43887844],
       [0.85859792, 0.69736803],
       [0.09417735, 0.97562235],
       [0.7611397 , 0.78606431],
       [0.12811363, 0.45038594],
       [0.37079802, 0.92676499],
       [0.64386512, 0.82276161],
       [0.4434142 , 0.22723872],
       [0.55458479, 0.06381726],
       [0.82763117, 0.6316644 ],
       [0.75808774, 0.35452597],
       [0.97069802, 0.89312112],
       [0.7783835 , 0.19463871],
       [0.466721  , 0.04380377],
       [0.15428949, 0.68304895],
       [0.74476216, 0.96750973],
       [0.32582536, 0.37045971],
       [0.46955581, 0.18947136],
       [0.12992151, 0.47570493],
       [0.22690935, 0.66981399],
       [0.43715192, 0.8326782 ],
       [0.7002651 , 0.31236664],
       [0.8322598 , 0.80476436],
       [0.38747838, 0.2883281 ],
       [0.6824955 , 0.13975248],
       [0.1999082 , 0.00736227],
       [0.78692438, 0.66485086],
       [0.70516538, 0.78072903],
       [0.45891578, 0.5687412 ],
       [0.139797  , 0.11453007],
       [0.

In [ ]:
ys_true

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
def decision_tree(x,branch_1, branch_2_1, branch_2_2):
    x0,x1 = x
    if x0 < branch_1:
        if x1 < branch_2_1:
            return 1
        else:
            return 0
    else:
        if x1 < branch_2_2:
            return 0
        else:
            return 0

In [ ]:
def sample_theta(size_of_theta):
    # Do NOT CHANGE.
    theta = np.random.uniform(0, 1, size=size_of_theta)
    return theta

In [ ]:
global_best_loss = float("inf")
global_best_theta = None

In [ ]:
def accuracy(predicts, real):
    right = 0
    wrong = 0
    attempts= 0
    for predict in real:
        attempts +=1
        if predicts[predict] == real:
            right +=1
        else:
            wrong += 1
    return (right/attempts) *100
        



In [ ]:
best_loss = float("inf")
for _ in range(10):
    best_theta = 
    for _ in tqdm.tqdm(range(100)):
        

        

    

In [ ]:


##################################
# here you implement a Decision Tree that is built using the fortuna algorithm.
# The depth of the tree should be less than 4
# The DT should reach 100% accuracy.





# Task 6 -- Best Route App

A company called Knut Knut Transport AS is using one of the 4 routes for delivery (see Pitch\_knutknut\_transport.pdf for more info).
* A -> C -> D  
* A -> C -> E  
* B -> C -> D  
* B -> C -> E  

They have discovered that they can transport the goods faster by picking the right route given 
only the depature time of the transport.

In the file "traffic.jsonl" on Canvas is the collected data up to the current point in time.
So far, they have just selected a route at random, now they want to implement a simple web-api
that can help the drivers select the best route. 

* Using the data found in traffic.jsonl, create a ML model that given an time (hour:min) can select the fastest route to travel. **Be sure to document in a google doc/word/notebook/... how YOU created your ML model.** The ML model should be trained using the Fortuna algorithm.

* Download the knut\_knut\_app.py found on canvas an implement the function: get\_the\_best\_route\_as\_a\_text\_informatic(dep\_hour, dep\_min) such that the web application works and gives a good estimated time.

* The CEO (Knut) want you to estimate how much time they can save from using this new app.
* Prepare a VERY short presentation (pdf) on the gains and tech behind the app (random subsample will present for the class)


Some hints:
* Look closely at the data using both numerical analysis and visual (plotting). 
* Use the python library datetime to handle time calculations. 
* Make sure the features are scaled in a way that make sense.
* Once you have a model working, use the python library pickle to save/load the model.